import os
import glob
import joblib

_model = None

def load_model():
    """Loads the model dynamically from the local MLflow registry store."""
    global _model
    if _model is None:
        try:
            # Dynamically fetch the latest model.pkl generated by FileStore in the mounted directory
            search_path = "/app/data/mlruns/**/model.pkl"
            models_found = glob.glob(search_path, recursive=True)
            
            if models_found:
                # Get the most recently modified model
                latest_model_path = max(models_found, key=os.path.getctime)
                _model = joblib.load(latest_model_path)
                print(f"Successfully loaded model from local mount: {latest_model_path}")
            else:
                _model = None
                print("Warning: Failed to locate any model.pkl files dynamically in /app/data/mlruns")
        except Exception as e:
            print(f"Warning: Exception loading model: {e}")
            _model = None
    return _model
